namespace Adeni.Infrastructure.Persistence;

/// <summary>Dev-only sample businesses — handcrafted anchors plus ~1k generated bulk entries.</summary>
internal static class DevelopmentSeedCatalog
{
    internal const int TargetTotalCount = 1000;

    internal sealed record SampleBusiness(
        string Slug,
        string Name,
        string LocationName,
        string MarketId,
        string CategorySlug,
        string Area,
        string AddressLine,
        double Latitude,
        double Longitude,
        string Phone,
        string Description,
        string ServiceName,
        string ServiceDescription,
        decimal PriceAmount,
        int DurationMinutes);

    internal static IReadOnlyList<SampleBusiness> All =>
        Anchors.Concat(DevelopmentSeedGenerator.GenerateBulk()).ToArray();

    private static readonly SampleBusiness[] Anchors =
    [
        // —— Lagos (GTM live — largest seed set) ——
        S("lekki-cuts", "Lekki Cuts", "Lekki", "lagos", "barbers", "Lekki Phase 1",
            "12 Admiralty Way, Lekki", 6.4474, 3.4700, "+2348012345678",
            "Walk-in fades and beard trims in Lekki. Book online — no long waits.",
            "Classic haircut", "Clippers, line-up, and hot towel finish.", 8000, 30),
        S("vi-fade-factory", "VI Fade Factory", "Victoria Island", "lagos", "barbers", "Victoria Island",
            "15 Akin Adesola Street, VI", 6.4281, 3.4219, "+2348023456789",
            "Premium fades and shaves on the island.",
            "Executive fade", "Skin fade with beard sculpt.", 10000, 45),
        S("ikeja-glam-studio", "Ikeja Glam Studio", "Ikeja", "lagos", "hair-salons", "Ikeja GRA",
            "22 Isaac John Street, Ikeja", 6.6018, 3.3515, "+2348034567890",
            "Silk press, braids, and colour in the mainland hub.",
            "Silk press", "Wash, blow-dry, and silk press finish.", 18000, 90),
        S("yaba-nail-lounge", "Yaba Nail Lounge", "Yaba", "lagos", "nail-spa", "Yaba",
            "8 Herbert Macaulay Way, Yaba", 6.5095, 3.3711, "+2348045678901",
            "Gel, acrylics, and pedicures near the tech corridor.",
            "Gel manicure", "Shape, cuticle care, and gel polish.", 12000, 60),
        S("ikoyi-beauty-bar", "Ikoyi Beauty Bar", "Ikoyi", "lagos", "makeup-brows", "Ikoyi",
            "3 Bourdillon Road, Ikoyi", 6.4549, 3.4246, "+2348056789012",
            "Brows, lashes, and event makeup.",
            "Brow shaping", "Thread or wax with tint optional.", 9000, 30),
        S("surulere-fades", "Surulere Fades", "Surulere", "lagos", "barbers", "Surulere",
            "55 Bode Thomas Street, Surulere", 6.4969, 3.3558, "+2348067890123",
            "Neighbourhood barbershop — sharp lines, fair prices.",
            "Shape up", "Haircut with edge-up and neck shave.", 6000, 30),
        S("ajah-braids-co", "Ajah Braids Co.", "Ajah", "lagos", "hair-salons", "Ajah",
            "14 Lekki-Epe Expressway, Ajah", 6.4683, 3.5852, "+2348078901234",
            "Knotless braids and twists on the peninsula.",
            "Knotless braids", "Medium length, hair included.", 35000, 180),
        S("maryland-spa-day", "Maryland Spa Day", "Maryland", "lagos", "nail-spa", "Maryland",
            "9 Ikorodu Road, Maryland", 6.5784, 3.3673, "+2348089012345",
            "Nails, waxing, and quick facials.",
            "Spa pedicure", "Soak, scrub, massage, and polish.", 15000, 75),
        S("lekki-brow-studio", "Lekki Brow Studio", "Lekki Phase 1", "lagos", "makeup-brows", "Lekki",
            "27 Admiralty Way, Lekki", 6.4420, 3.4720, "+2348090123456",
            "Microblading and lamination specialists.",
            "Brow lamination", "Lift, tint, and shape.", 22000, 45),
        S("ikeja-barber-hub", "Ikeja Barber Hub", "Ikeja", "lagos", "barbers", "Allen Avenue",
            "44 Allen Avenue, Ikeja", 6.5960, 3.3580, "+2348101234567",
            "Quick lunch-break cuts for professionals.",
            "Express cut", "Clippers cut and line-up.", 7000, 20),
        S("yaba-hair-lounge", "Yaba Hair Lounge", "Yaba", "lagos", "hair-salons", "Sabo",
            "2 Sabo-Yaba Road, Yaba", 6.5120, 3.3780, "+2348112345678",
            "Natural hair, locs, and protective styles.",
            "Wash & retwist", "Shampoo and loc retwist.", 14000, 75),
        S("lekki-nail-house", "Lekki Nail House", "Lekki", "lagos", "nail-spa", "Lekki Phase 1",
            "5 Fola Osibo Street, Lekki", 6.4490, 3.4680, "+2348123456780",
            "Luxury nail art and spa packages.",
            "Luxury manicure", "Full manicure with massage.", 16000, 60),

        // —— Abuja ——
        S("abuja-glow-salon", "Abuja Glow Salon", "Wuse", "abuja", "hair-salons", "Wuse 2",
            "44 Adetokunbo Ademola Crescent, Wuse 2", 9.0765, 7.3986, "+2348098765432",
            "Braids, silk press, and natural hair care in the capital.",
            "Wash & blowout", "Shampoo, deep condition, and styled blowout.", 15000, 60),
        S("garki-fades", "Garki Fades", "Garki", "abuja", "barbers", "Garki II",
            "18 Ahmadu Bello Way, Garki", 9.0400, 7.4900, "+2348134567890",
            "Clean fades in the heart of Garki.",
            "Low fade", "Low fade with beard trim.", 5000, 35),
        S("wuse-nail-spa", "Wuse Nail Spa", "Wuse", "abuja", "nail-spa", "Wuse",
            "10 Aminu Kano Crescent, Wuse", 9.0680, 7.4820, "+2348145678901",
            "Manicures and pedicures for Wuse professionals.",
            "Classic pedicure", "Foot soak, scrub, and polish.", 12000, 60),
        S("maitama-hair-atelier", "Maitama Hair Atelier", "Maitama", "abuja", "hair-salons", "Maitama",
            "6 Aguiyi Ironsi Street, Maitama", 9.0850, 7.4950, "+2348156789012",
            "Upscale colour and styling in Maitama.",
            "Colour & gloss", "Single-process colour with gloss.", 45000, 120),
        S("gwarinpa-beauty-bar", "Gwarinpa Beauty Bar", "Gwarinpa", "abuja", "makeup-brows", "Gwarinpa",
            "3 3rd Avenue, Gwarinpa", 9.1080, 7.3980, "+2348167890123",
            "Bridal and soft-glam makeup.",
            "Soft glam makeup", "Full face for events.", 25000, 60),

        // —— Ottawa ——
        S("ottawa-capitol-cuts", "Capitol Cuts", "Centretown", "ottawa", "barbers", "Centretown",
            "120 Bank Street, Ottawa", 45.4215, -75.6972, "+16135550101",
            "Neighbourhood barbershop steps from Parliament Hill.",
            "Men's haircut", "Scissor or clipper cut with neck shave.", 35, 30),
        S("byward-barber", "ByWard Barber", "ByWard Market", "ottawa", "barbers", "ByWard Market",
            "55 ByWard Market Square, Ottawa", 45.4275, -75.6930, "+16135550111",
            "Market district cuts and hot towel shaves.",
            "Beard trim", "Shape and line with hot towel.", 25, 20),
        S("glebe-hair-studio", "Glebe Hair Studio", "The Glebe", "ottawa", "hair-salons", "The Glebe",
            "680 Bank Street, Ottawa", 45.4030, -75.6880, "+16135550112",
            "Cuts and colour in the Glebe.",
            "Cut & colour", "Consultation, cut, and single-process colour.", 120, 90),
        S("westboro-nail-bar", "Westboro Nail Bar", "Westboro", "ottawa", "nail-spa", "Westboro",
            "350 Richmond Road, Ottawa", 45.3920, -75.7580, "+16135550113",
            "Nails and waxing in Westboro Village.",
            "Gel manicure", "Gel polish with shaping.", 45, 45),
        S("kanata-grooming", "Kanata Grooming", "Kanata", "ottawa", "barbers", "Kanata",
            "500 Earl Grey Drive, Kanata", 45.3080, -75.9180, "+16135550114",
            "Suburban barbershop for the whole family.",
            "Kids cut", "Under 12 clipper or scissor cut.", 28, 25),

        // —— Toronto ——
        S("toronto-annex-salon", "Annex Hair Studio", "The Annex", "toronto", "hair-salons", "The Annex",
            "402 Bloor Street West, Toronto", 43.6677, -79.4068, "+14165550102",
            "Colour, cuts, and styling near the University of Toronto.",
            "Cut & style", "Consultation, cut, and finish.", 85, 45),
        S("queen-west-cuts", "Queen West Cuts", "Queen West", "toronto", "barbers", "Queen West",
            "890 Queen Street West, Toronto", 43.6440, -79.4100, "+14165550121",
            "Creative cuts on Queen West.",
            "Scissor cut", "Layered scissor cut and style.", 55, 40),
        S("distiller-hair-co", "Distillery Hair Co.", "Distillery District", "toronto", "hair-salons", "Distillery",
            "15 Tank House Lane, Toronto", 43.6500, -79.3590, "+14165550122",
            "Boutique salon in the Distillery District.",
            "Blowout", "Shampoo and styled blowout.", 65, 45),
        S("yorkville-nail-spa", "Yorkville Nail Spa", "Yorkville", "toronto", "nail-spa", "Yorkville",
            "55 Avenue Road, Toronto", 43.6710, -79.3930, "+14165550123",
            "Luxury nails in Yorkville.",
            "Spa manicure", "Full manicure with paraffin.", 75, 60),
        S("kensington-brow-bar", "Kensington Brow Bar", "Kensington Market", "toronto", "makeup-brows", "Kensington",
            "200 Augusta Avenue, Toronto", 43.6540, -79.4020, "+14165550124",
            "Brows and lashes in Kensington Market.",
            "Lash lift", "Lift and tint.", 95, 60),

        // —— Houston ——
        S("houston-montrose-barber", "Montrose Barber Co.", "Montrose", "houston", "barbers", "Montrose",
            "888 Westheimer Road, Houston", 29.7420, -95.4010, "+17135550103",
            "Classic barbering in Montrose — hot lather shaves and fades.",
            "Skin fade", "Skin fade with beard trim.", 45, 45),
        S("heights-hair-studio", "Heights Hair Studio", "The Heights", "houston", "hair-salons", "The Heights",
            "500 W 19th Street, Houston", 29.8020, -95.4010, "+17135550131",
            "Colour and extensions in the Heights.",
            "Balayage", "Hand-painted highlights.", 180, 150),
        S("midtown-fades", "Midtown Fades", "Midtown", "houston", "barbers", "Midtown",
            "3400 Main Street, Houston", 29.7410, -95.3780, "+17135550132",
            "Walk-in fades near Midtown.",
            "Taper fade", "Taper with lineup.", 40, 35),
        S("rice-village-nails", "Rice Village Nails", "Rice Village", "houston", "nail-spa", "Rice Village",
            "2400 University Boulevard, Houston", 29.7170, -95.4030, "+17135550133",
            "Nails near Rice University.",
            "Acrylic full set", "Sculpted acrylics.", 65, 90),
        S("galleria-grooming", "Galleria Grooming", "Uptown", "houston", "barbers", "Uptown",
            "5085 Westheimer Road, Houston", 29.7390, -95.4620, "+17135550134",
            "Upscale grooming near the Galleria.",
            "Hot towel shave", "Straight-razor shave with hot towel.", 55, 30),

        // —— Dallas ——
        S("dallas-deep-ellum-cuts", "Deep Ellum Cuts", "Deep Ellum", "dallas", "barbers", "Deep Ellum",
            "2800 Main Street, Dallas", 32.7831, -96.7844, "+12145550104",
            "Modern cuts in Deep Ellum. Walk-ins welcome, booking preferred.",
            "Signature cut", "Cut, wash, and style.", 40, 30),
        S("uptown-salon-dallas", "Uptown Salon Dallas", "Uptown", "dallas", "hair-salons", "Uptown",
            "2500 Cedar Springs Road, Dallas", 32.8050, -96.8010, "+12145550141",
            "Full-service salon in Uptown Dallas.",
            "Cut & blowout", "Cut with styled blowout.", 95, 60),
        S("bishop-arts-barber", "Bishop Arts Barber", "Bishop Arts", "dallas", "barbers", "Bishop Arts",
            "408 N Bishop Avenue, Dallas", 32.7480, -96.8280, "+12145550142",
            "Classic barber chair vibes in Bishop Arts.",
            "Beard & cut combo", "Haircut with full beard service.", 50, 45),
        S("preston-nail-lounge", "Preston Nail Lounge", "Preston Hollow", "dallas", "nail-spa", "Preston Hollow",
            "5959 W Northwest Highway, Dallas", 32.8650, -96.8030, "+12145550143",
            "Nails and spa treatments in Preston Hollow.",
            "Deluxe pedicure", "Extended massage and polish.", 70, 75),
        S("frisco-fades", "Frisco Fades", "Frisco", "dallas", "barbers", "Frisco",
            "8888 Legacy Drive, Frisco", 33.1070, -96.8270, "+12145550144",
            "North Dallas suburban fades.",
            "Kids & adult cut", "One price any age.", 35, 30),
    ];

    private static SampleBusiness S(
        string slug,
        string name,
        string locationName,
        string marketId,
        string categorySlug,
        string area,
        string addressLine,
        double latitude,
        double longitude,
        string phone,
        string description,
        string serviceName,
        string serviceDescription,
        decimal priceAmount,
        int durationMinutes) =>
        new(
            slug,
            name,
            locationName,
            marketId,
            categorySlug,
            area,
            addressLine,
            latitude,
            longitude,
            phone,
            description,
            serviceName,
            serviceDescription,
            priceAmount,
            durationMinutes);
}
