namespace Adeni.Infrastructure.Persistence;

using Adeni.Domain.Booking;

/// <summary>
/// Dev sample businesses for the Beauty &amp; Wellness wedge: Lagos and Ottawa, enabled categories only.
/// </summary>
internal static class DevelopmentSeedCatalog
{
    internal static IReadOnlyList<SampleBusiness> All =>
        Anchors.Concat(DevelopmentSeedGenerator.GenerateBulk()).ToArray();

    internal sealed record SampleBusiness(
        string Slug,
        string Name,
        string LocationName,
        string MarketId,
        string CategorySlug,
        string Area,
        string AddressLine,
        double Latitude,
        double Longitude,
        string Phone,
        string Description,
        string ServiceName,
        string ServiceDescription,
        decimal PriceAmount,
        int DurationMinutes,
        string? CatalogServiceId = null,
        BookingDeliveryType BookingDeliveryType = BookingDeliveryType.Appointment);

    private static readonly SampleBusiness[] Anchors =
    [
        // Lagos — one named business per enabled category. lekki-cuts stays the dev-owner marker.
        S("lekki-cuts", "Lekki Cuts", "Lekki", "lagos", "hair-grooming", "Lekki Phase 1",
            "12 Admiralty Way, Lekki", 6.4474, 3.4700, "+2348012345678",
            "Fades, beard grooming, and line-ups in Lekki. Book online.",
            "Barbering", "Clipper cut, line-up, and hot towel finish.", 8000, 30,
            "hair-barbering"),
        S("vi-day-spa", "Victoria Island Day Spa", "Victoria Island", "lagos", "spa-relaxation", "Victoria Island",
            "15 Akin Adesola Street, VI", 6.4281, 3.4219, "+2348023456789",
            "Day spa and body treatments on the island.",
            "Day Spa Package", "Half-day spa with a body treatment and rest.", 45000, 120,
            "spa-day-package", BookingDeliveryType.Experience),
        S("ikeja-skin-studio", "Ikeja Skin Studio", "Ikeja", "lagos", "skincare-aesthetics", "Ikeja GRA",
            "22 Isaac John Street, Ikeja", 6.6018, 3.3515, "+2348034567890",
            "Facials, brows, and skin treatments in Ikeja.",
            "Facial", "Cleanse, treatment, and moisturize.", 18000, 60,
            "skin-facial"),
        S("yaba-nail-lounge", "Yaba Nail Lounge", "Yaba", "lagos", "nails", "Yaba",
            "8 Herbert Macaulay Way, Yaba", 6.5095, 3.3711, "+2348045678901",
            "Gel, manicures, and pedicures near the tech corridor.",
            "Gel Nails", "Shape, cuticle care, and gel polish.", 12000, 75,
            "nails-gel"),
        S("ikoyi-massage-studio", "Ikoyi Massage Studio", "Ikoyi", "lagos", "massage-bodywork", "Ikoyi",
            "3 Bourdillon Road, Ikoyi", 6.4549, 3.4246, "+2348056789012",
            "Swedish and deep tissue massage in Ikoyi.",
            "Deep Tissue Massage", "Focused pressure for tight muscles.", 25000, 60,
            "massage-deep-tissue"),
        S("surulere-strength", "Surulere Strength Co.", "Surulere", "lagos", "fitness", "Surulere",
            "55 Bode Thomas Street, Surulere", 6.4969, 3.3558, "+2348067890123",
            "Personal training and strength sessions in Surulere.",
            "Personal Training", "One-to-one strength session.", 15000, 60,
            "fitness-pt", BookingDeliveryType.Session),
        S("ajah-yoga-loft", "Ajah Yoga Loft", "Ajah", "lagos", "yoga", "Ajah",
            "14 Lekki-Epe Expressway, Ajah", 6.4683, 3.5852, "+2348078901234",
            "Yoga classes on the peninsula.",
            "Yoga Class", "Group yoga class.", 8000, 60,
            "yoga-group-class", BookingDeliveryType.Class),
        S("lekki-pilates", "Lekki Pilates House", "Lekki", "lagos", "pilates", "Lekki Phase 1",
            "22 Admiralty Way, Lekki", 6.4474, 3.4721, "+2348089012345",
            "Mat and reformer Pilates in Lekki.",
            "Pilates Class", "Group mat Pilates.", 12000, 55,
            "pilates-group-class", BookingDeliveryType.Class),

        // Ottawa — second launch market, same taxonomy.
        S("ottawa-capitol-cuts", "Capitol Cuts", "Centretown", "ottawa", "hair-grooming", "Centretown",
            "120 Bank Street, Ottawa", 45.4215, -75.6972, "+16135550101",
            "Neighbourhood grooming steps from Parliament Hill.",
            "Haircut", "Scissor or clipper cut with neck finish.", 40, 45,
            "hair-cut"),
        S("byward-massage", "ByWard Massage", "ByWard Market", "ottawa", "massage-bodywork", "ByWard Market",
            "55 ByWard Market Square, Ottawa", 45.4275, -75.6930, "+16135550111",
            "Relaxation and sports massage in the Market.",
            "Swedish Massage", "Full-body relaxation massage.", 110, 60,
            "massage-swedish"),
        S("glebe-spa", "Glebe Day Spa", "The Glebe", "ottawa", "spa-relaxation", "The Glebe",
            "680 Bank Street, Ottawa", 45.4030, -75.6880, "+16135550112",
            "Spa treatments in the Glebe.",
            "Body Treatment", "Scrub and massage treatment.", 130, 60,
            "spa-body-treatment"),
        S("westboro-nail-bar", "Westboro Nail Bar", "Westboro", "ottawa", "nails", "Westboro",
            "350 Richmond Road, Ottawa", 45.3920, -75.7580, "+16135550113",
            "Manicures and gel nails in Westboro Village.",
            "Manicure", "Classic manicure with polish.", 45, 45,
            "nails-manicure"),
        S("hintonburg-skin", "Hintonburg Skin", "Hintonburg", "ottawa", "skincare-aesthetics", "Hintonburg",
            "1080 Wellington Street West, Ottawa", 45.4015, -75.7260, "+16135550115",
            "Facials, brows, and lashes in Hintonburg.",
            "Brows & Lashes", "Shape, tint, and lash lift.", 85, 45,
            "skin-brows-lashes"),
        S("kanata-yoga", "Kanata Yoga", "Kanata", "ottawa", "yoga", "Kanata",
            "500 Earl Grey Drive, Kanata", 45.3080, -75.9180, "+16135550114",
            "Yoga and private sessions in Kanata.",
            "Private Yoga Session", "One-to-one yoga.", 90, 60,
            "yoga-private", BookingDeliveryType.Session),
        S("westboro-pilates", "Westboro Pilates", "Westboro", "ottawa", "pilates", "Westboro",
            "380 Richmond Road, Ottawa", 45.3915, -75.7565, "+16135550117",
            "Reformer and mat Pilates in Westboro Village.",
            "Reformer Pilates", "Guided reformer session.", 85, 50,
            "pilates-reformer", BookingDeliveryType.Class),
        S("orleans-fitness", "Orleans Fitness Lab", "Orleans", "ottawa", "fitness", "Orleans",
            "210 Centrum Boulevard, Ottawa", 45.4760, -75.5140, "+16135550116",
            "Strength and conditioning sessions in Orleans.",
            "Strength & Conditioning", "Coached strength session.", 70, 45,
            "fitness-strength", BookingDeliveryType.Session),
    ];

    private static SampleBusiness S(
        string slug,
        string name,
        string locationName,
        string marketId,
        string categorySlug,
        string area,
        string addressLine,
        double latitude,
        double longitude,
        string phone,
        string description,
        string serviceName,
        string serviceDescription,
        decimal priceAmount,
        int durationMinutes,
        string? catalogServiceId = null,
        BookingDeliveryType bookingDeliveryType = BookingDeliveryType.Appointment) =>
        new(
            slug,
            name,
            locationName,
            marketId,
            categorySlug,
            area,
            addressLine,
            latitude,
            longitude,
            phone,
            description,
            serviceName,
            serviceDescription,
            priceAmount,
            durationMinutes,
            catalogServiceId,
            bookingDeliveryType);
}
